// ─── Global Styles Object ─────────────────────────────────────────────────────
// All inline JS style objects used throughout the app live here so that
// component files stay clean and readable.

export const styles = {
  appWrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    overflow: 'hidden',
    background: 'var(--bg-deep, #08070d)',
  },
  container: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
    background: 'var(--bg-deep, #08070d)',
  },
  titlebar: {
    height: '48px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'var(--sidebar-bg, rgba(10, 9, 16, 0.82))',
    borderBottom: '1px solid rgba(255, 255, 255, 0.04)',
    padding: '0 10px 0 16px',
    userSelect: 'none',
    WebkitAppRegion: 'drag',
    zIndex: 1000,
    backdropFilter: 'blur(24px)',
  },
  titlebarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    WebkitAppRegion: 'no-drag',
  },
  titlebarBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginRight: '8px',
  },
  titlebarBrandText: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '14.5px',
    fontWeight: '700',
    color: '#f8fafc',
    letterSpacing: '-0.3px',
  },
  titlebarCenter: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0 20px',
  },
  titlebarSearchInner: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    borderRadius: '8px',
    padding: '4px 10px',
    width: '100%',
    maxWidth: '380px',
    WebkitAppRegion: 'no-drag',
    transition: 'all 0.2s ease',
  },
  titlebarSearchInput: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#f8fafc',
    outline: 'none',
    fontSize: '12.5px',
    fontWeight: '500',
    flex: 1,
    padding: 0,
  },
  titlebarRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    WebkitAppRegion: 'no-drag',
  },
  windowControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
    marginLeft: '4px',
    WebkitAppRegion: 'no-drag',
  },
  windowBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#94a3b8',
    transition: 'all 0.15s ease',
  },
  sidebar: {
    width: '260px',
    backgroundColor: 'var(--sidebar-bg, #12111b)',
    borderRight: '1px solid rgba(255, 255, 255, 0.04)',
    display: 'flex',
    flexDirection: 'column',
    padding: '0 0 24px 0',
    backdropFilter: 'blur(24px)',
    zIndex: 10,
  },
  sidebarHeader: {
    height: '56px',
    padding: '0 16px 0 20px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.04)',
    marginBottom: '20px',
  },
  sidebarHeaderText: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '15px',
    fontWeight: '700',
    color: '#f8fafc',
    letterSpacing: '-0.3px',
  },
  sidebarToggleBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    border: '1px solid transparent',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  badge: {
    fontSize: '9px',
    fontWeight: '800',
    backgroundColor: 'var(--accent, #8b5cf6)',
    color: '#ffffff',
    padding: '2px 6px',
    borderRadius: '99px',
    marginLeft: 'auto',
    letterSpacing: '0.5px',
  },
  sectionHeader: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: '0.5px',
    padding: '0 26px 10px 26px',
  },
  sidebarNav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    padding: '0 12px',
  },
  sidebarItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 14px',
    borderRadius: '10px',
    color: '#94a3b8',
    cursor: 'pointer',
    fontSize: '13.5px',
    fontWeight: '500',
    transition: 'all 0.15s ease',
    userSelect: 'none',
    border: '1px solid transparent',
  },
  activeSidebarItem: {
    backgroundColor: 'var(--accent-bg-faint, rgba(139,92,246,0.07))',
    border: '1px solid var(--accent-border, rgba(139,92,246,0.12))',
    color: 'var(--accent, #c084fc)',
  },
  itemCount: {
    marginLeft: 'auto',
    fontSize: '11px',
    color: '#475569',
    fontWeight: '700',
  },
  activeItemCount: {
    color: 'var(--accent, #c084fc)',
  },
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    position: 'relative',
  },
  mainSlider: {
    display: 'flex',
    flexDirection: 'row',
    width: '200%',
    height: '100%',
    flex: 1,
    minHeight: 0,
    transition: 'transform 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  mainPanel: {
    width: '50%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    height: '56px',
    padding: '0 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid rgba(255, 255, 255, 0.04)',
    position: 'relative',
    backgroundColor: 'rgba(10, 9, 16, 0.15)',
    backdropFilter: 'blur(8px)',
    zIndex: 100,
  },
  mainHeaderTitle: {
    position: 'absolute',
    left: '50%',
    transform: 'translateX(-50%)',
    fontFamily: "'Outfit', sans-serif",
    fontSize: '15px',
    fontWeight: '700',
    color: '#cbd5e1',
    pointerEvents: 'none',
    letterSpacing: '-0.3px',
  },
  searchBarRow: {
    backgroundColor: 'rgba(10, 9, 16, 0.4)',
    display: 'flex',
    alignItems: 'center',
    padding: '0 24px',
    overflow: 'hidden',
    backdropFilter: 'blur(10px)',
    position: 'relative',
    zIndex: 20,
  },
  searchBarInner: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    border: '1px solid rgba(255, 255, 255, 0.05)',
    borderRadius: '8px',
    padding: '4px 10px',
    width: '100%',
    maxWidth: '480px',
    margin: '0 auto',
  },
  searchBarInput: {
    backgroundColor: 'transparent',
    border: 'none',
    color: '#f8fafc',
    outline: 'none',
    fontSize: '13px',
    fontWeight: '500',
    flex: 1,
    padding: 0,
  },
  popover: {
    position: 'absolute',
    top: '46px',
    right: '0',
    width: '230px',
    backgroundColor: 'rgba(23, 23, 23, 0.95)',
    backdropFilter: 'blur(24px)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '12px',
    boxShadow: '0 12px 30px rgba(0, 0, 0, 0.6)',
    zIndex: 1000,
    overflow: 'visible',
    padding: '8px',
  },
  popoverArrow: {
    position: 'absolute',
    top: '-6px',
    right: '14px',
    width: '10px',
    height: '10px',
    backgroundColor: 'rgba(23, 23, 23, 0.95)',
    borderLeft: '1px solid rgba(255, 255, 255, 0.08)',
    borderTop: '1px solid rgba(255, 255, 255, 0.08)',
    transform: 'rotate(45deg)',
    zIndex: 999,
  },
  popoverLeft: {
    position: 'absolute',
    top: '46px',
    left: '0',
    width: '230px',
    backgroundColor: 'rgba(23, 23, 23, 0.95)',
    backdropFilter: 'blur(24px)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '12px',
    boxShadow: '0 12px 30px rgba(0, 0, 0, 0.6)',
    zIndex: 1000,
    overflow: 'visible',
    padding: '8px',
  },
  popoverArrowLeft: {
    position: 'absolute',
    top: '-6px',
    left: '14px',
    width: '10px',
    height: '10px',
    backgroundColor: 'rgba(23, 23, 23, 0.95)',
    borderLeft: '1px solid rgba(255, 255, 255, 0.08)',
    borderTop: '1px solid rgba(255, 255, 255, 0.08)',
    transform: 'rotate(45deg)',
    zIndex: 999,
  },
  popoverContent: {
    position: 'relative',
    zIndex: 1001,
  },
  popoverItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    borderRadius: '6px',
    color: '#cbd5e1',
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  popoverShortcut: {
    fontSize: '11px',
    color: '#64748b',
    fontWeight: '400',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    padding: '2px 6px',
    borderRadius: '4px',
    border: '1px solid rgba(255, 255, 255, 0.05)',
  },
  popoverSeparator: {
    height: '1px',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    margin: '4px 0',
  },
  shortcutsModal: {
    width: '400px',
    background: 'rgba(15, 12, 28, 0.88)',
    backdropFilter: 'blur(24px)',
    border: '1px solid rgba(139, 92, 246, 0.22)',
    boxShadow: '0 30px 60px rgba(0,0,0,0.8), 0 0 50px rgba(139, 92, 246, 0.12)',
    borderRadius: '16px',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    zIndex: 201,
  },
  shortcutsModalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid rgba(255, 255, 255, 0.05)',
    paddingBottom: '12px',
  },
  shortcutsModalTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#f8fafc',
    margin: 0,
  },
  modalCloseBtn: {
    cursor: 'pointer',
    color: '#94a3b8',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  headerActions: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
  },
  actionIconContainer: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    border: '1px solid transparent',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  actionIcon: {
    color: '#64748b',
  },
  gridContainer: {
    flex: 1,
    overflowY: 'auto',
    padding: '32px',
  },
  grid: {
    display: 'grid',
    gap: '28px',
  },
  gameCard: {
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '220px',
    width: '100%',
    margin: '0 auto',
  },
  coverWrapper: {
    borderRadius: '12px',
    overflow: 'hidden',
    position: 'relative',
    boxShadow: '0 12px 20px -8px rgba(0, 0, 0, 0.6)',
    border: '1px solid rgba(255, 255, 255, 0.04)',
    transition: 'all 0.25s cubic-bezier(0.25, 0.8, 0.25, 1)',
  },
  coverContainer: {
    position: 'relative',
    aspectRatio: '2/3',
    backgroundColor: '#07060a',
    overflow: 'hidden',
  },
  cover: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.4s ease',
  },
  coverPlaceholder: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, #100f23 0%, #1e092b 100%)',
    position: 'relative',
  },
  placeholderGlow: {
    position: 'absolute',
    width: '60px',
    height: '60px',
    borderRadius: '50%',
    background: '#7c3aed',
    filter: 'blur(30px)',
    opacity: 0.4,
  },
  placeholderText: {
    fontSize: '56px',
    fontFamily: "'Outfit', sans-serif",
    fontWeight: '800',
    color: 'rgba(255, 255, 255, 0.12)',
    zIndex: 1,
  },
  playOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0,
    transition: 'opacity 0.2s ease',
  },
  playButtonCircle: {
    width: '52px',
    height: '52px',
    borderRadius: '50%',
    backgroundColor: '#f8fafc',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 8px 20px rgba(124, 58, 237, 0.4)',
    transform: 'scale(0.85)',
    transition: 'transform 0.2s cubic-bezier(0.25, 0.8, 0.25, 1)',
  },
  editActionContainer: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    border: '1px solid rgba(255,255,255,0.06)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0,
    transform: 'scale(0.9)',
    transition: 'all 0.2s ease',
    backdropFilter: 'blur(8px)',
    zIndex: 5,
  },
  gameInfo: {
    marginTop: '12px',
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  gameTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontWeight: '600',
    color: '#cbd5e1',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    transition: 'color 0.2s ease',
  },
  gameSourceBadge: {
    fontSize: '8.5px',
    fontWeight: '800',
    color: '#475569',
    letterSpacing: '1px',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '14px',
  },
  loadingText: {
    fontSize: '14.5px',
    fontWeight: '500',
    color: '#475569',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    gap: '8px',
    padding: '40px',
  },
  emptyStateTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '16.5px',
    fontWeight: '600',
    color: '#475569',
  },
  emptyStateSub: {
    fontSize: '13px',
    color: '#334155',
    maxWidth: '280px',
  },
  toast: {
    position: 'absolute',
    top: '20px',
    left: '50%',
    backgroundColor: '#0f0e16',
    border: '1px solid rgba(139, 92, 246, 0.22)',
    boxShadow: '0 20px 30px -5px rgba(0,0,0,0.7), 0 0 30px rgba(139, 92, 246, 0.08)',
    borderRadius: '12px',
    padding: '12px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    zIndex: 100,
  },
  toastSuccess: {
    border: '1px solid rgba(74, 222, 128, 0.18)',
    boxShadow: '0 20px 30px -5px rgba(0,0,0,0.7), 0 0 30px rgba(74, 222, 128, 0.04)',
  },
  toastError: {
    border: '1px solid rgba(248, 113, 113, 0.18)',
    boxShadow: '0 20px 30px -5px rgba(0,0,0,0.7), 0 0 30px rgba(248, 113, 113, 0.04)',
  },
  toastText: {
    fontSize: '13.5px',
    fontWeight: '600',
    color: '#f8fafc',
  },
  spinner: {
    width: '14px',
    height: '14px',
    borderRadius: '50%',
    border: '2px solid rgba(255, 255, 255, 0.1)',
    borderTopColor: 'var(--accent, #c084fc)',
    animation: 'spin 0.8s linear infinite',
  },
  spinnerLarge: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    border: '3px solid rgba(139, 92, 246, 0.08)',
    borderTopColor: '#8b5cf6',
    animation: 'spin 1s linear infinite',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(5, 4, 10, 0.72)',
    backdropFilter: 'blur(16px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
  },
  modalContentLarge: {
    width: '900px',
    maxHeight: '90vh',
    background: 'rgba(15, 12, 28, 0.82)',
    border: '1px solid rgba(139, 92, 246, 0.22)',
    boxShadow: '0 30px 60px rgba(0,0,0,0.8), 0 0 50px rgba(139, 92, 246, 0.12)',
    borderRadius: '16px',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    fontFamily: "'Inter', sans-serif",
  },
  modalHeader: {
    padding: '20px 24px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.04)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '18px',
    fontWeight: '700',
    color: '#f8fafc',
    margin: 0,
  },
  closeBtn: {
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.02)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#64748b',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  settingsSecTitle: {
    fontFamily: "'Outfit', sans-serif",
    fontSize: '14.5px',
    fontWeight: '700',
    color: 'var(--accent, #c084fc)',
    margin: '0 0 4px 0',
    letterSpacing: '0.5px',
  },
  settingsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 0',
  },
  settingsLabel: {
    fontSize: '13.5px',
    fontWeight: '600',
    color: '#cbd5e1',
  },
  pillButton: {
    padding: '8px 16px',
    borderRadius: '8px',
    fontSize: '12.5px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  toggleButton: {
    padding: '8px 16px',
    borderRadius: '8px',
    fontSize: '12.5px',
    fontWeight: '700',
    width: '100px',
    textAlign: 'center',
    cursor: 'pointer',
  },
  formLayout: {
    display: 'flex',
    height: '520px',
    overflow: 'hidden',
  },
  formLeft: {
    flex: 1,
    padding: '24px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  formRight: {
    width: '420px',
    borderLeft: '1px solid rgba(255, 255, 255, 0.04)',
    background: 'rgba(5, 4, 10, 0.25)',
    padding: '24px',
    overflowY: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  formLabel: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#94a3b8',
  },
  formCoverStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'rgba(139, 92, 246, 0.05)',
    border: '1px solid rgba(139, 92, 246, 0.1)',
    borderRadius: '8px',
    padding: '10px 12px',
    marginTop: '6px',
  },
  formActions: {
    display: 'flex',
    gap: '12px',
    marginTop: 'auto',
    paddingTop: '20px',
  },
  formBtnSec: {
    flex: 1,
    padding: '12px',
    borderRadius: '10px',
    fontSize: '13.5px',
    fontWeight: '600',
    cursor: 'pointer',
    textAlign: 'center',
  },
  formBtnPri: {
    flex: 2,
    padding: '12px',
    borderRadius: '10px',
    fontSize: '13.5px',
    fontWeight: '700',
    cursor: 'pointer',
    textAlign: 'center',
  },
  formToggleBtn: {
    padding: '10px',
    borderRadius: '8px',
    fontSize: '12.5px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  sgdbSearchBtn: {
    padding: '0 18px',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sgdbEmpty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    padding: '0 32px',
  },
  sgdbResultsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    overflowY: 'auto',
    flex: 1,
  },
  sgdbResultItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px',
    background: 'rgba(255,255,255,0.01)',
    border: '1px solid rgba(255,255,255,0.03)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  sgdbResultName: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#cbd5e1',
  },
  selectedGameHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: '12px',
    borderBottom: '1px solid rgba(255,255,255,0.03)',
    marginBottom: '12px',
  },
  selectedGameLabel: {
    fontSize: '12px',
    color: '#94a3b8',
  },
  coversLoader: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: '8px',
  },
  coversGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
    overflowY: 'auto',
    flex: 1,
    padding: '2px',
    paddingRight: '6px',
    minHeight: 0,
  },
  coverThumbnailCard: {
    background: '#07060a',
    borderRadius: '10px',
    overflow: 'hidden',
    border: '1px solid rgba(255,255,255,0.03)',
    display: 'flex',
    flexDirection: 'column',
    height: '260px',
    position: 'relative',
  },
  coverThumbImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  coverThumbInfo: {
    position: 'absolute',
    bottom: 0, left: 0, right: 0,
    background: 'linear-gradient(to top, rgba(0,0,0,0.85) 0%, rgba(0,0,0,0) 100%)',
    padding: '12px 8px 8px 8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  coverThumbBadge: {
    fontSize: '8px',
    fontWeight: '700',
    color: 'var(--accent, #c084fc)',
    textShadow: '0 1px 2px rgba(0,0,0,0.8)',
  },
  applyCoverBtn: {
    padding: '6px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: '700',
    cursor: 'pointer',
    textAlign: 'center',
    background: 'var(--accent-bg-mid, rgba(167,139,250,0.12))',
    borderColor: 'var(--accent-border-strong, rgba(167,139,250,0.35))',
    color: 'var(--accent, #c084fc)',
  },
  // Unused legacy keys kept for reference — can be pruned in future
  hiddenManagerList: { display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '12px', flex: 1, overflowY: 'auto' },
  infoBox: { display: 'flex', gap: '8px', padding: '12px', background: 'rgba(139,92,246,0.05)', border: '1px solid rgba(139,92,246,0.12)', borderRadius: '8px', marginTop: '6px' },
  infoText: { fontSize: '11px', lineHeight: '1.4', color: '#94a3b8' },
}
